version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: retro_mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: retro_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: retro_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  api:
    build: .
    container_name: retro_api
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
      MONGO_DB_NAME: "retro_exchange"
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - mongo
      - kafka
    ports:
      - "8000:8000"

  email_service:
    build:
      context: ./email_service
    container_name: retro_email_service
    depends_on:
      - kafka

  nginx:
    image: nginx:latest
    container_name: retro_nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
